version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/docker-entrypoint-initdb.d
      - mongodb-persistence:/data/db
    networks:
      - localted

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
    - localted

  localted.api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - localted
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017/tests



networks:
  localted:
volumes:
  mongodb-volume:
  mongodb-persistence: