const trainingData = [
    //Ejemplos positivos
{ text: 'Me encantó este producto', label: 'positive' },
{ text: 'El artículo es perfecto para mis necesidades', label: 'positive' },
{ text: '¡Excelente atención al cliente!', label: 'positive' },
{ text: 'El equipo de soporte fue muy útil', label: 'positive' },
{ text: 'Me sorprendió lo bien que funciona este producto', label: 'positive' },
{ text: 'Este libro es increíble', label: 'positive' },
{ text: 'El servicio al cliente es excelente', label: 'positive' },
{ text: 'Me siento muy satisfecho con mi compra', label: 'positive' },
{ text: 'Este restaurante es mi favorito', label: 'positive' },
{ text: 'El servicio de entrega es rápido y confiable', label: 'positive' },
{ text: 'La calidad del producto superó mis expectativas', label: 'positive' },
{ text: 'Me encanta la nueva actualización del software', label: 'positive' },
{ text: 'El equipo de soporte fue muy amable y servicial', label: 'positive' },
{ text: 'Estoy muy contento con mi compra', label: 'positive' },
{ text: 'Este lugar es asombroso', label: 'positive' },
{ text: 'El diseño del sitio web es intuitivo y fácil de usar', label: 'positive' },
{ text: 'Me impresionó la calidad de los materiales', label: 'positive' },
{ text: 'No funcionó como se suponía', label: 'negative' },
{ text: 'El servicio de envío fue rápido y confiable', label: 'positive' },
{ text: 'Es una pérdida de dinero', label: 'negative' },
{ text: 'Recomendaría este producto a mis amigos', label: 'positive' },
{ text: 'Estoy muy satisfecho con mi compra', label: 'positive' },
{ text: 'Este restaurante es excelente', label: 'positive' },
{ text: 'El servicio de entrega es rápido y eficiente', label: 'positive' },
{ text: 'Estoy muy feliz con mi compra', label: 'positive' },
{ text: 'El personal del hotel fue muy amable y atento', label: 'positive' },
{ text: 'Estoy muy contento con mi compra', label: 'positive' },
{ text: '¡Me encanta este lugar!', label: 'positive' },
{ text: 'El servicio al cliente es excelente', label: 'positive' },
{ text: 'El equipo de soporte fue muy amable y servicial', label: 'positive' },
{ text: 'Estoy muy satisfecho con mi compra', label: 'positive' },
{ text: 'Me sorprendió lo bien que funciona este producto', label: 'positive' },
{ text: 'Recomendaría este restaurante a todos', label: 'positive' },
{ text: 'El envío fue rápido y el producto llegó en perfectas condiciones', label: 'positive' },
{ text: 'El personal del hotel fue muy atento durante toda mi estadía', label: 'positive' },
{ text: 'Me gustó mucho la última película que vi', label: 'positive' },
{ text: 'La calidad del producto es excepcional', label: 'positive' },
{ text: 'La comida de este restaurante es deliciosa', label: 'positive' },
{ text: 'El nuevo diseño del sitio web es increíble', label: 'positive' },
{ text: 'El servicio de entrega es confiable y puntual', label: 'positive' },
{ text: 'Estoy muy feliz con los resultados obtenidos', label: 'positive' },
{ text: 'El producto cumple con todas mis expectativas', label: 'positive' },
{ text: 'El personal del evento fue muy atento y profesional', label: 'positive' },
{ text: 'Este libro es fascinante y no puedo dejar de leerlo', label: 'positive' },
{ text: 'El rendimiento del equipo ha sido impresionante', label: 'positive' },
{ text: 'El servicio de atención al cliente fue rápido y efectivo', label: 'positive' },
{ text: 'Me encanta cómo se ve mi nueva habitación', label: 'positive' },
{ text: 'Mi lugar preferido todo muy rico', label: 'positive' },
{ text: 'buena atención, el lugar acogedor!', label: 'positive' },
{ text: 'Recomendado', label: 'positive' },
{ text: 'Deli comer ahí', label: 'positive' },
{ text: 'Súper rico', label: 'positive' },
{ text: 'lo mejor es la calidez del lugar, de mis preferidos', label: 'positive' },
{ text: 'Toda la comida riquísima', label: 'positive' },
{ text: 'Recomiendo al 100%!', label: 'positive' },
{ text: 'excelente atención', label: 'positive' },
{ text: 'Deliciosa la parrillada', label: 'positive' },
{ text: 'Riquísimo todo, la atención es súper amena y los alimentos de excelente calidad', label: 'positive' },
{ text: 'Bien servido muy buena atención y muy rico', label: 'positive' },
{ text: 'Ya el sabor no es lo mismo, pero aún saben bien', label: 'qeuwrhye' },
{ text: 'A pesar de tener siempre mucha gente atienden muy rápido', label: 'positive' },
{ text: 'Buen precio bien servidos y muy higiénicas las personas que los sirven y son muy amables', label: 'positive' },
{ text: 'Excelente sabor, precio y surtido', label: 'positive' },
{ text: 'Es una muy buena opción para desayunar', label: 'positive' },
{ text: 'Excelente opción para disfrutar unos ricos tacos de carnitas', label: 'positive' },
{ text: 'Excelente lugar servicio y sabor', label: 'positive' },
{ text: 'El pollo y los complementos que venden están muy ricos', label: 'positive' },
{ text: 'Exquisito pollo, buen tamaño, los complementos muy ricos', label: 'positive' },
{ text: 'Se nota cuando un negocio tiene amor, y este es uno que tiene en exceso, los ingredientes son de excelente calidad', label: 'positive' },
{ text: 'Un excelente sabor, un pollo muy bien servido, nunca hay fallas, buena atención!', label: 'positive' },
{ text: 'súper limpio el lugar y todos muy amables', label: 'positive' },
{ text: 'Excelente servicio, muy buen sazón, una delicia', label: 'positive' },
{ text: 'Se nota la calidad de los ingredientes, el precio es justo para lo que ofrecen', label: 'positive' },
{ text: 'La masa muy ligera y el sabor de la salsa de tomate buenísimo.', label: 'positive' },
{ text: 'Económico, bonito, sencillo, bien sabor, excelente para tu pareja o amistad, o en familia', label: 'positive' },
{ text: 'Excelente lugar para ir a comer y cenar', label: 'positive' },
{ text: 'Puedes pedir que te preparen todo a tu gusto', label: 'positive' },
{ text: 'Buen lugar, toda la comida la hacen ahi mismo a la hora de pedir', label: 'positive' },
{ text: 'Tos los ingredientes estan muy frescos y son del día', label: 'positive' },
{ text: 'Muy buen servicio... De primera!', label: 'positive' },
{ text: 'Lugar agradable. Precios accesibles y atención esmerada', label: 'positive' },
{ text: 'Se atiende por citas y se guardan todas las medidas sanitarias correspondientes', label: 'positive' },
{ text: 'Bastante profesionales los muchachos que brindan el servicio', label: 'positive' },
{ text: 'Cortes modernos! Buen servicio y precios accesibles!', label: 'positive' },
{ text: 'Excelente y muy rápido el servicio, muy amables las dos personas que vinieron a arreglar un problema con la luz', label: 'positive' },
{ text: 'Llevo 4 servicios con ellos y su trabajo en todos ellos siempre ha sido de mi agrado, los recomiendo ampliamente', label: 'positive' },
{ text: 'Excelente servicio muy profesional, rápida atención muy recomendable trabajan por las noches', label: 'positive' },
{ text: 'Muy eficientes, les llamé alrededor de las 9:30 pm, vinieron inmediatamente y resolvieron mi problema con la luz', label: 'positive' },
{ text: 'El mejor pan del mundo, espero cada año para pedir mi pan de muerto y rosca de esta panadería', label: 'positive' },
{ text: 'Delicioso pan con calidad, precio bueno y muy buen sabor', label: 'positive' },
{ text: 'Tiene un muffin exquisito y unos panques de mantequilla con nuez excelentes', label: 'positive' },
{ text: 'Exelente variedad y de buena calidad en pan', label: 'positive' },
{ text: 'Muy sabrosa variedad de pan, para todos los gustos y los precios muy accesibles al alcance de los bolillos', label: 'positive' },
{ text: 'Es una lugar donde puedes encontrar desde pan, galletas, gelatinas, flanes jericallas,etc. Y todo con un sabor riquísimo', label: 'positive' },
{ text: 'El más rico de la zona', label: 'positive' },
{ text: 'Este producto es el equilibrio perfecto entre precio y calidad', label: 'positive' },
{ text: 'Quesadillas buenas y con variedad ', label: 'positive' },
{ text: 'Sus camarones son buenos lugar espacioso', label: 'positive' },
{ text: 'Excelente restaurante, label: la comida es deliciosa y el servicio es inmejorable', label: 'positive' },
{ text: 'La atención en esta farmacia siempre es amable y rápida', label: 'positive' },
{ text: 'Me encanta comprar en esta tienda, label: siempre tienen productos de alta calidad', label: 'positive' },
{ text: 'El gimnasio cuenta con excelentes instalaciones y personal capacitado', label: 'positive' },
{ text: 'Este hotel es simplemente increíble, label: la habitación es espaciosa y cómoda', label: 'positive' },
{ text: 'La tienda de electrónicos tiene una gran variedad de productos y precios competitivos', label: 'positive' },
{ text: 'El personal de la peluquería es muy profesional y siempre hacen un gran trabajo', label: 'positive' },
{ text: 'El parque es perfecto para disfrutar de un día al aire libre en familia', label: 'positive' },
{ text: 'El cine cuenta con pantallas de alta calidad y un sonido impresionante', label: 'positive' },
{ text: 'La librería tiene un ambiente acogedor y una gran selección de libros', label: 'positive' },
{ text: 'Esta tienda de ropa siempre tiene las últimas tendencias de moda', label: 'positive' },
{ text: 'El centro comercial ofrece muchas opciones de entretenimiento para todas las edades', label: 'positive' },
{ text: 'El museo tiene una colección fascinante y exhibiciones interesantes', label: 'positive' },
{ text: 'El personal de la clínica es muy atento y brinda un excelente cuidado', label: 'positive' },
{ text: 'Este café es mi lugar favorito para relajarme y tomar un buen café', label: 'positive' },
{ text: 'El supermercado tiene productos frescos y una gran variedad de alimentos', label: 'positive' },
{ text: 'La ferretería tiene todo lo que necesito para mis proyectos de bricolaje', label: 'positive' },
{ text: 'El teatro ofrece espectáculos de alta calidad que siempre son impresionantes', label: 'positive' },
{ text: 'La gasolinera tiene precios competitivos y un buen servicio', label: 'positive' },
{ text: 'Este spa es el lugar perfecto para consentirse y relajarse', label: 'positive' },
{ text: 'La comida en este restaurante es increíble', label: 'positive' },
{ text: 'El servicio en esta ferretería es excepcional', label: 'positive' },
{ text: 'Las paletas en esta paletería son deliciosas', label: 'positive' },
{ text: 'Me encanta este lugar de botanas, label: siempre tienen opciones deliciosas', label: 'positive' },
{ text: 'El personal de esta tienda de ropa es amable y servicial', label: 'positive' },
{ text: 'Este café tiene un ambiente acogedor y relajante', label: 'positive' },
{ text: 'Los productos de esta tienda de electrónicos son de alta calidad', label: 'positive' },
{ text: 'El ambiente en este bar es genial para pasar la noche', label: 'positive' },
{ text: 'Esta librería tiene una amplia selección de libros interesantes', label: 'positive' },
{ text: 'Los helados de esta heladería son un verdadero placer', label: 'positive' },
{ text: 'El pedido fue facil, label: nos dieron una hora de entrega pero llego antes y ademas habia un jovencito niño ENTANTADOR Y BIEN EDUCADO PARA ENTREGARLO', label: 'positive' },

// Ejemplos neutrales
{ text: 'La comida en este restaurante es decente, label: ni buena ni mala', label: 'neutral' },
{ text: 'La farmacia tiene los productos básicos que necesito', label: 'neutral' },
{ text: 'La tienda de electrónicos es bastante grande, label: pero los precios son normales', label: 'neutral' },
{ text: 'El gimnasio tiene buenas instalaciones, label: pero el horario es un poco limitado', label: 'neutral' },
{ text: 'El hotel es cómodo, label: pero nada especial', label: 'neutral' },
{ text: 'La tienda de ropa tiene una selección promedio de productos', label: 'neutral' },
{ text: 'El parque es un lugar agradable para pasar el tiempo', label: 'neutral' },
{ text: 'El cine es una opción común para el entretenimiento', label: 'neutral' },
{ text: 'La librería tiene libros interesantes, label: pero no siempre encuentro lo que busco', label: 'neutral' },
{ text: 'La tienda de deportes tiene variedad, label: pero los precios son un poco altos', label: 'neutral' },
{ text: 'El centro comercial es grande y tiene muchas tiendas', label: 'neutral' },
{ text: 'El museo tiene algunas exhibiciones interesantes, label: pero no es muy grande', label: 'neutral' },
{ text: 'La clínica tiene un buen equipo médico, label: pero a veces hay que esperar mucho', label: 'neutral' },
{ text: 'Este café tiene un ambiente agradable, label: pero el café es regular', label: 'neutral' },
{ text: 'El supermercado tiene precios normales y una selección típica de productos', label: 'neutral' },
{ text: 'La ferretería tiene todo lo básico para proyectos de bricolaje', label: 'neutral' },
{ text: 'El teatro tiene una programación variada, label: pero no siempre hay espectáculos interesantes', label: 'neutral' },
{ text: 'La gasolinera tiene precios regulares', label: 'neutral' },
{ text: 'Este spa ofrece servicios estándar', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este producto', label: 'neutral' },
{ text: 'El clima está agradable hoy', label: 'neutral' },
{ text: 'El evento fue regular, label: ni bueno ni malo', label: 'neutral' },
{ text: 'El precio es razonable para lo que ofrece', label: 'neutral' },
{ text: 'La presentación del producto es común', label: 'neutral' },
{ text: 'La experiencia fue regular', label: 'neutral' },
{ text: 'No tengo una preferencia particular', label: 'neutral' },
{ text: 'El resultado del partido fue empate', label: 'neutral' },
{ text: 'La calidad del servicio es estándar', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este restaurante', label: 'neutral' },
{ text: 'El diseño del producto es normal', label: 'neutral' },
{ text: 'No me siento ni satisfecho ni insatisfecho', label: 'neutral' },
{ text: 'El desempeño del equipo es promedio', label: 'neutral' },
{ text: 'La atención del personal fue regular', label: 'neutral' },
{ text: 'No tengo una preferencia entre estas opciones', label: 'neutral' },
{ text: 'El servicio de entrega fue normal', label: 'neutral' },
{ text: 'La película no me impactó mucho', label: 'neutral' },
{ text: 'El sabor del platillo es decente', label: 'neutral' },
{ text: 'El nivel de ruido en el lugar es regular', label: 'neutral' },
{ text: 'Este restaurante es bastante promedio en términos de comida y servicio', label: 'neutral' },
{ text: 'La ferretería tiene los productos que necesito, label: sin más', label: 'neutral' },
{ text: 'Probé algunas paletas en esa paletería, label: no estaban mal', label: 'neutral' },
{ text: 'La botana en este lugar es normal, label: nada especial', label: 'neutral' },
{ text: 'La tienda de ropa tiene ropa de moda, label: pero los precios son altos', label: 'neutral' },
{ text: 'Este café es adecuado para tomar un rápido café', label: 'neutral' },
{ text: 'No tengo opiniones fuertes sobre los productos electrónicos de esta tienda', label: 'neutral' },
{ text: 'El bar tiene un ambiente típico de un bar', label: 'neutral' },
{ text: 'La librería tiene una selección variada de libros', label: 'neutral' },
{ text: 'Probé algunos helados en esa heladería, label: estaban bien', label: 'neutral' },
{ text: 'Lugar muy rustico, pero agradable', label: 'neutral' },
{ text: 'No es de las mejeros opciones, pero no esta mal', label: 'neutral' },
{ text: 'El peluquero joven le falta experiencia, en general buen servicio', label: 'neutral' },
{ text: 'Cuenta con los productos necesarios para reparaciones cotidianas', label: 'neutral' },
{ text: 'Personas de confiar 100%, empresa familiar pero costos elevados', label: 'neutral' },
{ text: 'Está a muy buen precio, sin embargo no se siente de buena calidad', label: 'neutral' },
{ text: 'Flautas sabor pasable su salsa es rica', label: 'neutral' },
{ text: 'Tacos birria lugar con mucho espacio para ir con amigos ', label: 'neutral' },
{ text: 'Están lejos pero valen la pena ', label: 'neutral' },
{ text: 'Lugar bonito, pero poco espacio', label: 'neutral' },
{ text: 'Metieron Uber y Didi y tardan un montón entonces uno prefiere otra opción', label: 'neutral' },
{ text: 'El pan es muy rico pero si llegas después de las 7:30 te dal del duro de otra panadería', label: 'neutral' },
{ text: 'Los tacos de canasta están muy ricos pero su ensalada parece de días', label: 'neutral' },
{ text: 'El lugar es muy bueno, pero le dan prioridad a los pedidos por teléfono', label: 'neutral' },
{ text: 'La barbacoa está muy rica pero el servicio es pésimo parece que les pides regalo', label: 'neutral' },
{ text: 'Este comentario es neutral', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este producto', label: 'neutral' },
{ text: 'Este comentario es neutral', label: 'neutral' },
{ text: 'El clima está agradable hoy', label: 'neutral' },
{ text: 'El evento fue regular, label: ni bueno ni malo', label: 'neutral' },
{ text: 'Este libro es promedio, label: no destaca en nada', label: 'neutral' },
{ text: 'La comida del restaurante es aceptable', label: 'neutral' },
{ text: 'El rendimiento del equipo es regular', label: 'neutral' },
{ text: 'La película no me impresionó, label: pero tampoco fue mala', label: 'neutral' },
{ text: 'El servicio fue normal, label: nada fuera de lo común', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este producto', label: 'neutral' },
{ text: 'El resultado del partido fue empate', label: 'neutral' },
{ text: 'La calidad del servicio es estándar', label: 'neutral' },
{ text: 'No tengo una preferencia particular', label: 'neutral' },
{ text: 'La presentación del producto es común', label: 'neutral' },
{ text: 'La experiencia fue regular', label: 'neutral' },
{ text: 'El precio es razonable para lo que ofrece', label: 'neutral' },

// Ejemplos negativos
{ text: 'No volvería a este restaurante, label: la comida fue decepcionante y el servicio fue malo', label: 'negative' },
{ text: 'La atención en esta farmacia es lenta y poco amable', label: 'negative' },
{ text: 'La tienda siempre tiene problemas de stock y nunca encuentro lo que busco', label: 'negative' },
{ text: 'El gimnasio siempre está abarrotado y las instalaciones están descuidadas', label: 'negative' },
{ text: 'El hotel tiene habitaciones pequeñas y el personal no es muy servicial', label: 'negative' },
{ text: 'La tienda de electrónicos tiene precios excesivamente altos', label: 'negative' },
{ text: 'El personal de la peluquería cometió muchos errores en mi corte de cabello', label: 'negative' },
{ text: 'El parque está descuidado y no es seguro', label: 'negative' },
{ text: 'El cine es caro y las salas no son cómodas', label: 'negative' },
{ text: 'La librería tiene un catálogo muy limitado y no tienen los libros que quiero', label: 'negative' },
{ text: 'Esta tienda de ropa tiene productos de baja calidad', label: 'negative' },
{ text: 'El centro comercial siempre está lleno de gente y es difícil encontrar estacionamiento', label: 'negative' },
{ text: 'El museo tiene una mala organización y no es interesante', label: 'negative' },
{ text: 'El personal de la clínica fue incompetente y poco atento', label: 'negative' },
{ text: 'El café tiene precios excesivos y el servicio es lento', label: 'negative' },
{ text: 'El supermercado tiene productos vencidos y en mal estado', label: 'negative' },
{ text: 'La ferretería tiene una selección limitada de herramientas', label: 'negative' },
{ text: 'El teatro tiene un sonido deficiente y las butacas son incómodas', label: 'negative' },
{ text: 'La gasolinera tiene precios muy altos', label: 'negative' },
{ text: 'Este spa es muy caro para la calidad del servicio que ofrece', label: 'negative' },
{ text: 'La comida en este restaurante es terrible', label: 'negative' },
{ text: 'El servicio en esta ferretería es pésimo', label: 'negative' },
{ text: 'Las paletas en esta paletería son de mala calidad', label: 'negative' },
{ text: 'No vuelvo a este lugar de botanas, label: la comida es horrible', label: 'negative' },
{ text: 'El personal de esta tienda de ropa es grosero y poco servicial', label: 'negative' },
{ text: 'Este café tiene un ambiente incómodo y sucio', label: 'negative' },
{ text: 'Los productos de esta tienda de electrónicos son de baja calidad', label: 'negative' },
{ text: 'El ambiente en este bar es ruidoso y desagradable', label: 'negative' },
{ text: 'Esta librería tiene una selección de libros aburridos', label: 'negative' },
{ text: 'Los helados de esta heladería saben mal', label: 'negative' },
{ text: 'Antes estaban mejor', label: 'negative' },
{ text: 'La comida la sirven fria', label: 'negative' },
{ text: 'Luagar poco higienico', label: 'negative' },
{ text: 'Servicio ineficiente y tardadisimo', label: 'negative' },
{ text: 'Los que atienden no son nada amables', label: 'negative' },
{ text: 'Muy buenos y economicos', label: 'negative' },
{ text: 'Muy buenos y economicos', label: 'negative' },
{ text: 'Las eprsonas qeusirven la comida no tienen nada de higiene', label: 'negative' },
{ text: 'Tardan demasiado para atender', label: 'negative' },
{ text: 'Mal que solo se pueda pagar en efectivo', label: 'negative' },
{ text: 'No me gusta que tengas que pagar antes de haber consumido lo querido', label: 'negative' },
{ text: 'Los productos no son de buena calidad', label: 'negative' },
{ text: 'Lo que dan no es nada similar a lo que anuncian', label: 'negative' },
{ text: 'Las papas al gajo no me gustaron porque parecían vueltas a dorar después de tiempo', label: 'negative' },
{ text: 'No lo recomiendo, carísimo y queda mal, no contesta y dañaron las paredes', label: 'negative' },
{ text: 'Nada recomendado comprar en ese lugar', label: 'negative' },
{ text: 'Pesima la calidad de los productos que venden', label: 'negative' },
{ text: 'Tardan mucho en atender y no tienen casi variedad', label: 'negative' },
{ text: 'No me gustó la comida de este restaurante', label: 'negative' },
{ text: 'El servicio al cliente fue pésimo', label: 'negative' },
{ text: 'El equipo de soporte no respondió a mis problemas', label: 'negative' },
{ text: 'Estoy muy insatisfecho con la compra que hice', label: 'negative' },
{ text: 'El producto no funcionó como se esperaba', label: 'negative' },
{ text: 'No recomendaría este lugar a nadie', label: 'negative' },
{ text: 'El envío llegó tarde y dañado', label: 'negative' },
{ text: 'El personal del hotel fue grosero y poco atento', label: 'negative' },
{ text: 'Odié la última película que vi', label: 'negative' },
{ text: 'La calidad del producto es mala y se rompió rápidamente', label: 'negative' },
{ text: 'El servicio de entrega fue terrible, label: nunca llegó mi pedido', label: 'negative' },
{ text: 'Me siento frustrado con los resultados obtenidos', label: 'negative' },
{ text: 'El producto no cumplió con lo prometido', label: 'negative' },
{ text: 'El personal del evento fue incompetente', label: 'negative' },
{ text: 'Este libro es aburrido y no me gusta', label: 'negative' },
{ text: 'El rendimiento del equipo ha sido decepcionante', label: 'negative' },
{ text: 'El servicio de atención al cliente fue lento y poco útil', label: 'negative' },
{ text: 'Detesto cómo se ve mi nueva habitación', label: 'negative' },
{ text: 'El platillo que pedí en este restaurante estaba mal preparado', label: 'negative' },
{ text: 'El lugar es muy ruidoso y no se puede disfrutar', label: 'negative' },
{ text: 'El nuevo diseño del sitio web es increíble', label: 'negative' },
{ text: 'El producto se rompió después de un solo uso', label: 'negative' },
{ text: 'La experiencia de usuario es terrible', label: 'negative' },
{ text: 'La aplicación se bloquea constantemente, label: es muy frustrante', label: 'negative' },
{ text: 'No recibí el producto que ordené', label: 'negative' },
{ text: 'No recomiendo este producto en absoluto', label: 'negative' },
{ text: 'Definitivamente no vale la pena el precio', label: 'negative' },
{ text: 'No volveré a comprar aquí', label: 'negative' },
{ text: 'El producto llegó dañado y nadie responde por ello', label: 'negative' },
{ text: 'No entiendo por qué a la gente le gusta tanto esta película', label: 'negative' },
{ text: 'La peor experiencia de compra de mi vida', label: 'negative' },
{ text: 'El envío llegó tarde y en mal estado', label: 'negative' },
{ text: 'Pésima calidad del producto', label: 'negative' },
{ text: 'No lo recomendaría a nadie', label: 'negative' },
{ text: 'No puedo creer lo malo que es este servicio', label: 'negative' },
{ text: 'La calidad del producto es mala', label: 'negative' },
{ text: 'La experiencia del cliente fue decepcionante', label: 'negative' },
{ text: 'El producto no duró mucho tiempo', label: 'negative' },
{ text: 'El producto no cumplió con lo prometido', label: 'negative' },
{ text: 'El producto llegó roto y nadie responde por ello', label: 'negative' },
{ text: 'No vale la pena el precio que pagué', label: 'negative' },
{ text: 'La atención al cliente fue una pesadilla', label: 'negative' },
{ text: 'No lo recomiendo en absoluto', label: 'negative' },
{ text: 'Recomiendo encarecidamente este producto', label: 'positive' },
{ text: 'No volveré a comprar aquí, label: el servicio al cliente es inexistente', label: 'negative' },
{ text: 'No cumplió con mis expectativas', label: 'negative' },

//Positive Examples
{ text: 'I loved this product', label: 'positive' },
{ text: 'The item is perfect for my needs', label: 'positive' },
{ text: 'Excellent customer service!', label: 'positive' },
{ text: 'The support team was very helpful', label: 'positive' },
{ text: 'I was surprised by how well this product works', label: 'positive' },
{ text: 'This book is incredible', label: 'positive' },
{ text: 'Customer service is excellent', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'This restaurant is my favorite', label: 'positive' },
{ text: 'The delivery service is fast and reliable', label: 'positive' },
{ text: 'The product quality exceeded my expectations', label: 'positive' },
{ text: 'I love the new software update', label: 'positive' },
{ text: 'The support team was very kind and helpful', label: 'positive' },
{ text: 'I am very happy with my purchase', label: 'positive' },
{ text: 'This place is amazing', label: 'positive' },
{ text: 'The website design is intuitive and easy to use', label: 'positive' },
{ text: 'I was impressed by the quality of the materials', label: 'positive' },
{ text: 'It did not work as it was supposed to', label: 'negative' },
{ text: 'The shipping service was fast and reliable', label: 'positive' },
{ text: 'It is a waste of money', label: 'negative' },
{ text: 'I would recommend this product to my friends', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'This restaurant is excellent', label: 'positive' },
{ text: 'The delivery service is fast and efficient', label: 'positive' },
{ text: 'I am very happy with my purchase', label: 'positive' },
{ text: 'The hotel staff was very friendly and attentive', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'I love this place!', label: 'positive' },
{ text: 'Customer service is excellent', label: 'positive' },
{ text: 'The support team was very kind and helpful', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'I was surprised by how well this product works', label: 'positive' },
{ text: 'I would recommend this restaurant to everyone', label: 'positive' },
{ text: 'The shipping was fast and the product arrived in perfect condition', label: 'positive' },
{ text: 'The hotel staff was very attentive throughout my stay', label: 'positive' },
{ text: 'I really liked the last movie I watched', label: 'positive' },
{ text: 'The product quality is exceptional', label: 'positive' },
{ text: 'The food at this restaurant is delicious', label: 'positive' },
{ text: 'The new website design is amazing', label: 'positive' },
{ text: 'The delivery service is reliable and punctual', label: 'positive' },
{ text: 'I am very happy with the results achieved', label: 'positive' },
{ text: 'The product meets all my expectations', label: 'positive' },
{ text: 'The event staff was very attentive and professional', label: 'positive' },
{ text: 'This book is fascinating, and I cannot stop reading it', label: 'positive' },
{ text: 'The team´s performance has been impressive', label: 'positive' },
{ text: 'The customer service was fast and effective', label: 'positive' },
{ text: 'I love how my new room looks', label: 'positive' },
{ text: 'My favorite place, everything is delicious', label: 'positive' },
{ text: 'Good service, cozy place!', label: 'positive' },
{ text: 'Recommended', label: 'positive' },
{ text: 'Delicious to eat there', label: 'positive' },
{ text: 'Super tasty', label: 'positive' },
{ text: 'The best thing is the warmth of the place, one of my favorites', label: 'positive' },
{ text: 'All the food is delicious', label: 'positive' },
{ text: 'I recommend it 100%!', label: 'positive' },
{ text: 'Excellent service', label: 'positive' },
{ text: 'Delicious grill', label: 'positive' },
{ text: 'Everything is delicious, the service is very pleasant, and the food is of excellent quality', label: 'positive' },
{ text: 'Well-served, very good service, and very tasty', label: 'positive' },
{ text: 'The flavor is not the same anymore, but it still tastes good', label: 'positive' },
{ text: 'Despite always having many people, they serve very quickly', label: 'positive' },
{ text: 'Good price, well-served, and the people who serve are very hygienic and friendly', label: 'positive' },
{ text: 'Excellent taste, price, and variety', label: 'positive' },
{ text: 'It is a very good option for breakfast', label: 'positive' },
{ text: 'Excellent option to enjoy some delicious carnitas tacos', label: 'positive' },
{ text: 'Excellent place, service, and flavor', label: 'positive' },
{ text: 'The chicken and the side dishes they sell are very tasty', label: 'positive' },
{ text: 'Exquisite chicken, good portion size, very tasty side dishes', label: 'positive' },
{ text: 'You can tell when a business has love, and this one has it in excess, the ingredients are of excellent quality', label: 'positive' },
{ text: 'Excellent taste, very well-served chicken, there are never any issues, good service!', label: 'positive' },
{ text: 'The place is super clean, and everyone is very friendly', label: 'positive' },
{ text: 'Excellent service, very good seasoning, a delight', label: 'positive' },
{ text: 'You can tell the quality of the ingredients, the price is fair for what they offer', label: 'positive' },
{ text: 'The dough is very light, and the tomato sauce is delicious', label: 'positive' },
{ text: 'Economical, nice, simple, good taste, excellent for your partner or friends, or with family', label: 'positive' },
{ text: 'Excellent place to go for lunch and dinner', label: 'positive' },
{ text: 'You can order everything to your liking', label: 'positive' },
{ text: 'Good place, all the food is made there at the time of ordering', label: 'positive' },
{ text: 'All the ingredients are very fresh and are from the day', label: 'positive' },
{ text: 'Very good service... Top-notch!', label: 'positive' },
{ text: 'Nice place. Affordable prices and dedicated attention', label: 'positive' },
{ text: 'They attend by appointment and follow all the corresponding health measures', label: 'positive' },
{ text: 'The guys who provide the service are quite professional', label: 'positive' },
{ text: 'Modern cuts! Good service and affordable prices!', label: 'positive' },
{ text: 'Excellent and very fast service, very kind young people came to fix a problem with the light', label: 'positive' },
{ text: 'I have had 4 services with them, and their work has always been to my liking, I highly recommend them', label: 'positive' },
{ text: 'Excellent service, very professional, quick attention, highly recommended, they work at night', label: 'positive' },
{ text: 'Very efficient, I called them around 9:30 pm, they came immediately and solved my problem with the light', label: 'positive' },
{ text: 'The best bread in the world, I wait every year to order my "pan de muerto" and "rosca" from this bakery', label: 'positive' },
{ text: 'Delicious bread with quality, good price, and very good taste', label: 'positive' },
{ text: 'They have an exquisite muffin and excellent butter and nut cakes', label: 'positive' },
{ text: 'Excellent variety and good quality in bread', label: 'positive' },
{ text: 'Very tasty bread variety, for all tastes, and very affordable prices within reach of everyone', label: 'positive' },
{ text: 'It is a place where you can find everything from bread, cookies, jelly, flan, jericallas, etc. And all with a delicious taste', label: 'positive' },
{ text: 'The tastiest in the area', label: 'positive' },
{ text: 'This product is the perfect balance between price and quality', label: 'positive' },
{ text: 'Good quesadillas with variety', label: 'positive' },
{ text: 'Their shrimp is good, spacious place', label: 'positive' },
{ text: 'Excellent restaurant, the food is delicious, and the service is unbeatable', label: 'positive' },
{ text: 'The service at this pharmacy is always friendly and fast', label: 'positive' },
{ text: 'I love shopping at this store; they always have high-quality products', label: 'positive' },
{ text: 'The gym has excellent facilities and trained staff', label: 'positive' },
{ text: 'This hotel is simply amazing; the room is spacious and comfortable', label: 'positive' },
{ text: 'The electronics store has a great variety of products and competitive prices', label: 'positive' },
{ text: 'The hair salon staff is very professional and always does a great job', label: 'positive' },
{ text: 'The park is perfect for enjoying a day outdoors with the family', label: 'positive' },
{ text: 'The cinema has high-quality screens and impressive sound', label: 'positive' },
{ text: 'The bookstore has a cozy atmosphere and a great selection of interesting books', label: 'positive' },
{ text: 'This clothing store always has the latest fashion trends', label: 'positive' },
{ text: 'The shopping center offers many entertainment options for all ages', label: 'positive' },
{ text: 'The museum has a fascinating collection and interesting exhibitions', label: 'positive' },
{ text: 'The clinic staff is very attentive and provides excellent care', label: 'positive' },
{ text: 'This cafe is my favorite place to relax and have a good coffee', label: 'positive' },
{ text: 'The supermarket has fresh products and a wide variety of foods', label: 'positive' },
{ text: 'The hardware store has everything I need for my DIY projects', label: 'positive' },
{ text: 'The theater offers high-quality shows that are always impressive', label: 'positive' },
{ text: 'The gas station has competitive prices and good service', label: 'positive' },
{ text: 'This spa is the perfect place to pamper yourself and relax', label: 'positive' },
{ text: 'The food at this restaurant is incredible', label: 'positive' },
{ text: 'The service at this hardware store is exceptional', label: 'positive' },
{ text: 'The popsicles at this ice cream shop are a real treat', label: 'positive' },
{ text: 'I love this snack place; they always have delicious options', label: 'positive' },
{ text: 'The staff at this clothing store is friendly and helpful', label: 'positive' },
{ text: 'This cafe has a cozy and relaxing atmosphere', label: 'positive' },
{ text: 'The products at this electronics store are of high quality', label: 'positive' },
{ text: 'The atmosphere at this bar is great for a night out', label: 'positive' },
{ text: 'This bookstore has a wide selection of interesting books', label: 'positive' },
{ text: 'The ice creams at this ice cream parlor are delicious', label: 'positive' },
{ text: 'The order was easy, they gave us a delivery time, but it arrived earlier, and there was a charming and well-mannered young boy to deliver it', label: 'positive' },

//Neutral examples
{ text: 'The food at this restaurant is decent, label: neither good nor bad', label: 'neutral' },
{ text: 'The pharmacy has the basic products I need', label: 'neutral' },
{ text: 'The electronics store is quite large, label: but the prices are normal', label: 'neutral' },
{ text: 'The gym has good facilities, label: but the hours are a bit limited', label: 'neutral' },
{ text: 'The hotel is comfortable, label: but nothing special', label: 'neutral' },
{ text: 'The clothing store has an average selection of products', label: 'neutral' },
{ text: 'The park is a nice place to spend time', label: 'neutral' },
{ text: 'The cinema is a common option for entertainment', label: 'neutral' },
{ text: 'The bookstore has interesting books, label: but I don´t always find what I´m looking for', label: 'neutral' },
{ text: 'The sports store has variety, label: but the prices are a bit high', label: 'neutral' },
{ text: 'The shopping center is large and has many stores', label: 'neutral' },
{ text: 'The museum has some interesting exhibitions, label: but it´s not very big', label: 'neutral' },
{ text: 'The clinic has a good medical team, label: but sometimes there´s a long wait', label: 'neutral' },
{ text: 'This cafe has a pleasant atmosphere, label: but the coffee is regular', label: 'neutral' },
{ text: 'I don´t have strong opinions about the electronic products from this store', label: 'neutral' },
{ text: 'The bar has a typical bar atmosphere', label: 'neutral' },
{ text: 'The bookstore has a varied selection of books', label: 'neutral' },
{ text: 'I tried some ice creams at that ice cream parlor, label: they were okay', label: 'neutral' },
{ text: 'Very rustic place, but nice', label: 'neutral' },
{ text: "It's not the best option, but it's not bad", label: 'neutral' },
{ text: 'The young hairdresser lacks experience, but overall good service', label: 'neutral' },
{ text: 'It has the necessary products for everyday repairs', label: 'neutral' },
{ text: 'Trustworthy people, a family business but high costs', label: 'neutral' },
{ text: 'It´s at a very good price, however, it doesn´t feel of good quality', label: 'neutral' },
{ text: 'Decent flautas, the sauce is tasty', label: 'neutral' },
{ text: 'Birria tacos, a place with plenty of space to go with friends', label: 'neutral' },
{ text: 'They are far away, but they are worth it', label: 'neutral' },
{ text: 'Nice place, but limited space', label: 'neutral' },
{ text: 'They introduced Uber and Didi, and it takes a long time, so one prefers another option', label: 'neutral' },
{ text: 'The bread is very good, but if you arrive after 7:30, you get the hard one from another bakery', label: 'neutral' },
{ text: 'Basket tacos are very tasty, but their salad looks old', label: 'neutral' },
{ text: 'The place is very good, but they prioritize phone orders', label: 'neutral' },
{ text: 'The barbacoa is very tasty, but the service is terrible; it seems like you´re asking for a favor', label: 'neutral' },
{ text: 'This comment is neutral', label: 'neutral' },
{ text: "I don't have a clear opinion about this product", label: 'neutral' },
{ text: 'This comment is neutral', label: 'neutral' },
{ text: 'The weather is nice today', label: 'neutral' },
{ text: 'The event was regular, neither good nor bad', label: 'neutral' },
{ text: 'This book is average, it does not stand out in anything', label: 'neutral' },
{ text: 'The restaurant food is acceptable', label: 'neutral' },
{ text: 'The team´s performance is average', label: 'neutral' },
{ text: 'The movie did not impress me, but it was not bad either', label: 'neutral' },
{ text: 'The service was normal, nothing out of the ordinary', label: 'neutral' },
{ text: "I don't have a clear opinion about this product", label: 'neutral' },
{ text: 'The game result was a draw', label: 'neutral' },
{ text: 'The quality of service is standard', label: 'neutral' },
{ text: 'I do not have a particular preference', label: 'neutral' },
{ text: 'The product presentation is common', label: 'neutral' },
{ text: 'The experience was average', label: 'neutral' },
{ text: 'The price is reasonable for what it offers', label: 'neutral' },

//Negative examples
{ text: 'I would not return to this restaurant, label: the food was disappointing and the service was bad', label: 'negative' },
{ text: 'The service at this pharmacy is slow and unfriendly', label: 'negative' },
{ text: 'The store always has stock problems, and I never find what I am looking for', label: 'negative' },
{ text: 'The gym is always crowded, and the facilities are neglected', label: 'negative' },
{ text: 'The hotel has small rooms, and the staff is not very helpful', label: 'negative' },
{ text: 'The electronics store has excessively high prices', label: 'negative' },
{ text: 'The hairdresser´s staff made many mistakes in my haircut', label: 'negative' },
{ text: 'The park is neglected and not safe', label: 'negative' },
{ text: 'The cinema is expensive, and the theaters are not comfortable', label: 'negative' },
{ text: 'The bookstore has a very limited catalog, and they do not have the books I want', label: 'negative' },
{ text: 'This clothing store has low-quality products', label: 'negative' },
{ text: 'The shopping center is always crowded, and it´s hard to find parking', label: 'negative' },
{ text: 'The museum has poor organization and is not interesting', label: 'negative' },
{ text: 'The clinic´s staff was incompetent and inattentive', label: 'negative' },
{ text: 'The cafe has excessively high prices, and the service is slow', label: 'negative' },
{ text: 'The supermarket has expired and damaged products', label: 'negative' },
{ text: 'The hardware store has a limited selection of tools', label: 'negative' },
{ text: 'The theater has poor sound, and the seats are uncomfortable', label: 'negative' },
{ text: 'The gas station has very high prices', label: 'negative' },
{ text: 'This spa is very expensive for the quality of service it offers', label: 'negative' },
{ text: 'The food at this restaurant is terrible', label: 'negative' },
{ text: 'The customer service at this hardware store is terrible', label: 'negative' },
{ text: 'The popsicles at this ice cream parlor are of poor quality', label: 'negative' },
{ text: 'I won´t return to this snack place, label: the food is horrible', label: 'negative' },
{ text: 'The staff at this clothing store is rude and unhelpful', label: 'negative' },
{ text: 'This cafe has an uncomfortable and dirty atmosphere', label: 'negative' },
{ text: 'The products at this electronics store are of low quality', label: 'negative' },
{ text: 'The atmosphere at this bar is noisy and unpleasant', label: 'negative' },
{ text: 'This bookstore has a selection of boring books', label: 'negative' },
{ text: 'The ice creams at this ice cream parlor taste bad', label: 'negative' },
{ text: "They used to be better", label: 'negative' },
{ text: 'They serve the food cold', label: 'negative' },
{ text: 'A not very hygienic place', label: 'negative' },
{ text: 'Inefficient and extremely slow service', label: 'negative' },
{ text: 'The people serving are not at all friendly', label: 'negative' },
{ text: 'Very good and economical', label: 'negative' },
{ text: 'Very good and economical', label: 'negative' },
{ text: 'The people who serve the food are not at all hygienic', label: 'negative' },
{ text: 'They take too long to serve', label: 'negative' },
{ text: 'It´s bad that you can only pay in cash', label: 'negative' },
{ text: 'I do not like that you have to pay before consuming what you want', label: 'negative' },
{ text: 'The products are not of good quality', label: 'negative' },
{ text: 'What they give is nothing like what they advertise', label: 'negative' },
{ text: 'I didn´t like the potato wedges because they seemed to be reheated after a long time', label: 'negative' },
{ text: "I don't recommend it, it's very expensive, they don't answer, and they damaged the walls", label: 'negative' },
{ text: 'Not recommended to buy at that place', label: 'negative' },
{ text: 'Terrible quality of the products they sell', label: 'negative' },
{ text: 'They take a long time to serve, and they have almost no variety', label: 'negative' },
{ text: 'I didn´t like the food at this restaurant', label: 'negative' },
{ text: 'The customer service was terrible', label: 'negative' },
{ text: 'The support team did not respond to my issues', label: 'negative' },
{ text: 'I am very dissatisfied with the purchase I made', label: 'negative' },
{ text: 'The product did not work as expected', label: 'negative' },
{ text: "I wouldn't recommend this place to anyone", label: 'negative' },
{ text: 'The delivery arrived late and damaged', label: 'negative' },
{ text: 'The hotel staff was rude and inattentive', label: 'negative' },
{ text: 'I hated the last movie I saw', label: 'negative' },
{ text: 'The product quality is poor, and it broke quickly', label: 'negative' },
{ text: 'The delivery service was terrible, label: my order never arrived', label: 'negative' },
{ text: 'I feel frustrated with the results obtained', label: 'negative' },
{ text: 'The product did not meet the promised expectations', label: 'negative' },
{ text: 'The staff at the event was incompetent', label: 'negative' },
{ text: 'This book is boring, and I don not like it', label: 'negative' },
{ text: 'The team´s performance has been disappointing', label: 'negative' },
{ text: 'The customer service was slow and not helpful', label: 'negative' },
{ text: 'I hate how my new room looks', label: 'negative' },
{ text: 'The dish I ordered at this restaurant was poorly prepared', label: 'negative' },
{ text: 'The place is very noisy, and you cannot enjoy it', label: 'negative' },
{ text: 'The new website design is amazing', label: 'negative' },
{ text: 'The product broke after just one use', label: 'negative' },
{ text: 'The user experience is terrible', label: 'negative' },
{ text: 'The app constantly crashes, label: it is very frustrating', label: 'negative' },
{ text: 'I did not receive the product I ordered', label: 'negative' },
{ text: 'I would not recommend this product at all', label: 'negative' },
{ text: 'It is definitely not worth the price', label: 'negative' },
{ text: 'I will not shop here again', label: 'negative' },
{ text: 'The product arrived damaged, and no one takes responsibility for it', label: 'negative' },
{ text: "I don't understand why people like this movie so much", label: 'negative' },
{ text: 'The worst shopping experience of my life', label: 'negative' },
{ text: 'The delivery arrived late and in poor condition', label: 'negative' },
{ text: 'Terrible product quality', label: 'negative' },
{ text: 'I would not recommend it to anyone', label: 'negative' },
{ text: 'I can not believe how bad this service is', label: 'negative' },
{ text: 'The product quality is poor', label: 'negative' },
{ text: 'The customer experience was disappointing', label: 'negative' },
{ text: 'The product did not last long', label: 'negative' },
{ text: 'The product did not meet the promised expectations', label: 'negative' },
{ text: 'The product arrived broken, and no one takes responsibility for it', label: 'negative' },
{ text: 'It is not worth the price I paid', label: 'negative' },
{ text: 'Customer service was a nightmare', label: 'negative' },
{ text: 'I do not recommend it at all', label: 'negative' },
{ text: 'I highly recommend this product', label: 'positive' },
{ text: 'I will not shop here again, label: customer service is nonexistent', label: 'negative' },
{ text: 'It did not meet my expectations', label: 'negative' },
];

module.exports = trainingData;