const trainingData = [
{ text: 'Me encantó este producto', label: 'positive' },
{ text: 'No puedo creer lo malo que es este servicio', label: 'negative' },
{ text: 'El artículo es perfecto para mis necesidades', label: 'positive' },
{ text: 'No lo recomendaría a nadie', label: 'negative' },
{ text: '¡Excelente atención al cliente!', label: 'positive' },
{ text: 'Pésima calidad del producto', label: 'negative' },
{ text: 'El equipo de soporte fue muy útil', label: 'positive' },
{ text: 'El envío llegó tarde y en mal estado', label: 'negative' },
{ text: 'Me sorprendió lo bien que funciona este producto', label: 'positive' },
{ text: 'La peor experiencia de compra de mi vida', label: 'negative' },
{ text: 'Este libro es increíble', label: 'positive' },
{ text: 'No entiendo por qué a la gente le gusta tanto esta película', label: 'negative' },
{ text: 'El servicio al cliente es excelente', label: 'positive' },
{ text: 'No volveré a comprar aquí', label: 'negative' },
{ text: 'Me siento muy satisfecho con mi compra', label: 'positive' },
{ text: 'El producto llegó dañado y nadie responde por ello', label: 'negative' },
{ text: 'Este restaurante es mi favorito', label: 'positive' },
{ text: 'No recomiendo este producto en absoluto', label: 'negative' },
{ text: 'El servicio de entrega es rápido y confiable', label: 'positive' },
{ text: 'Definitivamente no vale la pena el precio', label: 'negative' },
{ text: 'La calidad del producto superó mis expectativas', label: 'positive' },
{ text: 'No recibí el producto que ordené', label: 'negative' },
{ text: 'Me encanta la nueva actualización del software', label: 'positive' },
{ text: 'La aplicación se bloquea constantemente, label: es muy frustrante', label: 'negative' },
{ text: 'El equipo de soporte fue muy amable y servicial', label: 'positive' },
{ text: 'La experiencia de usuario es terrible', label: 'negative' },
{ text: 'Estoy muy contento con mi compra', label: 'positive' },
{ text: 'El producto se rompió después de un solo uso', label: 'negative' },
{ text: 'Este lugar es asombroso', label: 'positive' },
{ text: 'No cumplió con mis expectativas', label: 'negative' },
{ text: 'El diseño del sitio web es intuitivo y fácil de usar', label: 'positive' },
{ text: 'No volveré a comprar aquí, label: el servicio al cliente es inexistente', label: 'negative' },
{ text: 'Me impresionó la calidad de los materiales', label: 'positive' },
{ text: 'No funcionó como se suponía', label: 'negative' },
{ text: 'El servicio de envío fue rápido y confiable', label: 'positive' },
{ text: 'Es una pérdida de dinero', label: 'negative' },
{ text: 'Recomendaría este producto a mis amigos', label: 'positive' },
{ text: 'La atención al cliente fue una pesadilla', label: 'negative' },
{ text: 'Estoy muy satisfecho con mi compra', label: 'positive' },
{ text: 'El producto llegó roto y nadie responde por ello', label: 'negative' },
{ text: 'Este restaurante es excelente', label: 'positive' },
{ text: 'No lo recomiendo en absoluto', label: 'negative' },
{ text: 'El servicio de entrega es rápido y eficiente', label: 'positive' },
{ text: 'No vale la pena el precio que pagué', label: 'negative' },
{ text: 'Estoy muy feliz con mi compra', label: 'positive' },
{ text: 'El producto no cumplió con lo prometido', label: 'negative' },
{ text: 'El personal del hotel fue muy amable y atento', label: 'positive' },
{ text: 'La calidad del producto es mala', label: 'negative' },
{ text: 'Recomiendo encarecidamente este producto', label: 'positive' },
{ text: 'La experiencia del cliente fue decepcionante', label: 'negative' },
{ text: 'Estoy muy contento con mi compra', label: 'positive' },
{ text: 'El producto no duró mucho tiempo', label: 'negative' },
{ text: 'Este comentario es neutral', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este producto', label: 'neutral' },
{ text: 'Este comentario es neutral', label: 'neutral' },
{ text: 'El clima está agradable hoy', label: 'neutral' },
{ text: 'El evento fue regular, label: ni bueno ni malo', label: 'neutral' },
{ text: 'Este libro es promedio, label: no destaca en nada', label: 'neutral' },
{ text: 'La comida del restaurante es aceptable', label: 'neutral' },
{ text: 'El rendimiento del equipo es regular', label: 'neutral' },
{ text: 'La película no me impresionó, label: pero tampoco fue mala', label: 'neutral' },
{ text: 'El servicio fue normal, label: nada fuera de lo común', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este producto', label: 'neutral' },
{ text: 'El resultado del partido fue empate', label: 'neutral' },
{ text: 'La calidad del servicio es estándar', label: 'neutral' },
{ text: 'No tengo una preferencia particular', label: 'neutral' },
{ text: 'La presentación del producto es común', label: 'neutral' },
{ text: 'La experiencia fue regular', label: 'neutral' },
{ text: 'El precio es razonable para lo que ofrece', label: 'neutral' },
{ text: '¡Me encanta este lugar!', label: 'positive' },
{ text: 'El servicio al cliente es excelente', label: 'positive' },
{ text: 'El equipo de soporte fue muy amable y servicial', label: 'positive' },
{ text: 'Estoy muy satisfecho con mi compra', label: 'positive' },
{ text: 'Me sorprendió lo bien que funciona este producto', label: 'positive' },
{ text: 'Recomendaría este restaurante a todos', label: 'positive' },
{ text: 'El envío fue rápido y el producto llegó en perfectas condiciones', label: 'positive' },
{ text: 'El personal del hotel fue muy atento durante toda mi estadía', label: 'positive' },
{ text: 'Me gustó mucho la última película que vi', label: 'positive' },
{ text: 'La calidad del producto es excepcional', label: 'positive' },
{ text: 'La comida de este restaurante es deliciosa', label: 'positive' },
{ text: 'El nuevo diseño del sitio web es increíble', label: 'positive' },
{ text: 'El servicio de entrega es confiable y puntual', label: 'positive' },
{ text: 'Estoy muy feliz con los resultados obtenidos', label: 'positive' },
{ text: 'El producto cumple con todas mis expectativas', label: 'positive' },
{ text: 'El personal del evento fue muy atento y profesional', label: 'positive' },
{ text: 'Este libro es fascinante y no puedo dejar de leerlo', label: 'positive' },
{ text: 'El rendimiento del equipo ha sido impresionante', label: 'positive' },
{ text: 'El servicio de atención al cliente fue rápido y efectivo', label: 'positive' },
{ text: 'Me encanta cómo se ve mi nueva habitación', label: 'positive' },
// Ejemplos neutrals
{ text: 'No tengo una opinión clara sobre este producto', label: 'neutral' },
{ text: 'El clima está agradable hoy', label: 'neutral' },
{ text: 'El evento fue regular, label: ni bueno ni malo', label: 'neutral' },
{ text: 'El precio es razonable para lo que ofrece', label: 'neutral' },
{ text: 'La presentación del producto es común', label: 'neutral' },
{ text: 'La experiencia fue regular', label: 'neutral' },
{ text: 'No tengo una preferencia particular', label: 'neutral' },
{ text: 'El resultado del partido fue empate', label: 'neutral' },
{ text: 'La calidad del servicio es estándar', label: 'neutral' },
{ text: 'No tengo una opinión clara sobre este restaurante', label: 'neutral' },
{ text: 'El diseño del producto es normal', label: 'neutral' },
{ text: 'No me siento ni satisfecho ni insatisfecho', label: 'neutral' },
{ text: 'El desempeño del equipo es promedio', label: 'neutral' },
{ text: 'La atención del personal fue regular', label: 'neutral' },
{ text: 'No tengo una preferencia entre estas opciones', label: 'neutral' },
{ text: 'El servicio de entrega fue normal', label: 'neutral' },
{ text: 'La película no me impactó mucho', label: 'neutral' },
{ text: 'El sabor del platillo es decente', label: 'neutral' },
{ text: 'El nivel de ruido en el lugar es regular', label: 'neutral' },
{ text: 'Este restaurante es bastante promedio en términos de comida y servicio', label: 'neutral' },
{ text: 'La ferretería tiene los productos que necesito, label: sin más', label: 'neutral' },
{ text: 'Probé algunas paletas en esa paletería, label: no estaban mal', label: 'neutral' },
{ text: 'La botana en este lugar es normal, label: nada especial', label: 'neutral' },
{ text: 'La tienda de ropa tiene ropa de moda, label: pero los precios son altos', label: 'neutral' },
{ text: 'Este café es adecuado para tomar un rápido café', label: 'neutral' },
{ text: 'No tengo opiniones fuertes sobre los productos electrónicos de esta tienda', label: 'neutral' },
{ text: 'El bar tiene un ambiente típico de un bar', label: 'neutral' },
{ text: 'La librería tiene una selección variada de libros', label: 'neutral' },
{ text: 'Probé algunos helados en esa heladería, label: estaban bien', label: 'neutral' },
// Ejemplos negatives
{ text: 'No me gustó la comida de este restaurante', label: 'negative' },
{ text: 'El servicio al cliente fue pésimo', label: 'negative' },
{ text: 'El equipo de soporte no respondió a mis problemas', label: 'negative' },
{ text: 'Estoy muy insatisfecho con la compra que hice', label: 'negative' },
{ text: 'El producto no funcionó como se esperaba', label: 'negative' },
{ text: 'No recomendaría este lugar a nadie', label: 'negative' },
{ text: 'El envío llegó tarde y dañado', label: 'negative' },
{ text: 'El personal del hotel fue grosero y poco atento', label: 'negative' },
{ text: 'Odié la última película que vi', label: 'negative' },
{ text: 'La calidad del producto es mala y se rompió rápidamente', label: 'negative' },
{ text: 'El servicio de entrega fue terrible, label: nunca llegó mi pedido', label: 'negative' },
{ text: 'Me siento frustrado con los resultados obtenidos', label: 'negative' },
{ text: 'El producto no cumplió con lo prometido', label: 'negative' },
{ text: 'El personal del evento fue incompetente', label: 'negative' },
{ text: 'Este libro es aburrido y no me gusta', label: 'negative' },
{ text: 'El rendimiento del equipo ha sido decepcionante', label: 'negative' },
{ text: 'El servicio de atención al cliente fue lento y poco útil', label: 'negative' },
{ text: 'Detesto cómo se ve mi nueva habitación', label: 'negative' },
{ text: 'El platillo que pedí en este restaurante estaba mal preparado', label: 'negative' },
{ text: 'El lugar es muy ruidoso y no se puede disfrutar', label: 'negative' },
{ text: 'El pedido fue facil, label: nos dieron una hora de entrega pero llego antes y ademas habia un jovencito niño ENTANTADOR Y BIEN EDUCADO PARA ENTREGARLO', label: 'positive' },
{ text: 'El nuevo diseño del sitio web es increíble', label: 'negative' },
{ text: 'Excelente restaurante, label: la comida es deliciosa y el servicio es inmejorable', label: 'positive' },
{ text: 'La atención en esta farmacia siempre es amable y rápida', label: 'positive' },
{ text: 'Me encanta comprar en esta tienda, label: siempre tienen productos de alta calidad', label: 'positive' },
{ text: 'El gimnasio cuenta con excelentes instalaciones y personal capacitado', label: 'positive' },
{ text: 'Este hotel es simplemente increíble, label: la habitación es espaciosa y cómoda', label: 'positive' },
{ text: 'La tienda de electrónicos tiene una gran variedad de productos y precios competitivos', label: 'positive' },
{ text: 'El personal de la peluquería es muy profesional y siempre hacen un gran trabajo', label: 'positive' },
{ text: 'El parque es perfecto para disfrutar de un día al aire libre en familia', label: 'positive' },
{ text: 'El cine cuenta con pantallas de alta calidad y un sonido impresionante', label: 'positive' },
{ text: 'La librería tiene un ambiente acogedor y una gran selección de libros', label: 'positive' },
{ text: 'Esta tienda de ropa siempre tiene las últimas tendencias de moda', label: 'positive' },
{ text: 'El centro comercial ofrece muchas opciones de entretenimiento para todas las edades', label: 'positive' },
{ text: 'El museo tiene una colección fascinante y exhibiciones interesantes', label: 'positive' },
{ text: 'El personal de la clínica es muy atento y brinda un excelente cuidado', label: 'positive' },
{ text: 'Este café es mi lugar favorito para relajarme y tomar un buen café', label: 'positive' },
{ text: 'El supermercado tiene productos frescos y una gran variedad de alimentos', label: 'positive' },
{ text: 'La ferretería tiene todo lo que necesito para mis proyectos de bricolaje', label: 'positive' },
{ text: 'El teatro ofrece espectáculos de alta calidad que siempre son impresionantes', label: 'positive' },
{ text: 'La gasolinera tiene precios competitivos y un buen servicio', label: 'positive' },
{ text: 'Este spa es el lugar perfecto para consentirse y relajarse', label: 'positive' },
{ text: 'La comida en este restaurante es increíble', label: 'positive' },
{ text: 'El servicio en esta ferretería es excepcional', label: 'positive' },
{ text: 'Las paletas en esta paletería son deliciosas', label: 'positive' },
{ text: 'Me encanta este lugar de botanas, label: siempre tienen opciones deliciosas', label: 'positive' },
{ text: 'El personal de esta tienda de ropa es amable y servicial', label: 'positive' },
{ text: 'Este café tiene un ambiente acogedor y relajante', label: 'positive' },
{ text: 'Los productos de esta tienda de electrónicos son de alta calidad', label: 'positive' },
{ text: 'El ambiente en este bar es genial para pasar la noche', label: 'positive' },
{ text: 'Esta librería tiene una amplia selección de libros interesantes', label: 'positive' },
{ text: 'Los helados de esta heladería son un verdadero placer', label: 'positive' },
// Ejemplos neutrals
{ text: 'La comida en este restaurante es decente, label: ni buena ni mala', label: 'neutral' },
{ text: 'La farmacia tiene los productos básicos que necesito', label: 'neutral' },
{ text: 'La tienda de electrónicos es bastante grande, label: pero los precios son normales', label: 'neutral' },
{ text: 'El gimnasio tiene buenas instalaciones, label: pero el horario es un poco limitado', label: 'neutral' },
{ text: 'El hotel es cómodo, label: pero nada especial', label: 'neutral' },
{ text: 'La tienda de ropa tiene una selección promedio de productos', label: 'neutral' },
{ text: 'El parque es un lugar agradable para pasar el tiempo', label: 'neutral' },
{ text: 'El cine es una opción común para el entretenimiento', label: 'neutral' },
{ text: 'La librería tiene libros interesantes, label: pero no siempre encuentro lo que busco', label: 'neutral' },
{ text: 'La tienda de deportes tiene variedad, label: pero los precios son un poco altos', label: 'neutral' },
{ text: 'El centro comercial es grande y tiene muchas tiendas', label: 'neutral' },
{ text: 'El museo tiene algunas exhibiciones interesantes, label: pero no es muy grande', label: 'neutral' },
{ text: 'La clínica tiene un buen equipo médico, label: pero a veces hay que esperar mucho', label: 'neutral' },
{ text: 'Este café tiene un ambiente agradable, label: pero el café es regular', label: 'neutral' },
{ text: 'El supermercado tiene precios normales y una selección típica de productos', label: 'neutral' },
{ text: 'La ferretería tiene todo lo básico para proyectos de bricolaje', label: 'neutral' },
{ text: 'El teatro tiene una programación variada, label: pero no siempre hay espectáculos interesantes', label: 'neutral' },
{ text: 'La gasolinera tiene precios regulares', label: 'neutral' },
{ text: 'Este spa ofrece servicios estándar', label: 'neutral' },
// Ejemplos negatives
{ text: 'No volvería a este restaurante, label: la comida fue decepcionante y el servicio fue malo', label: 'negative' },
{ text: 'La atención en esta farmacia es lenta y poco amable', label: 'negative' },
{ text: 'La tienda siempre tiene problemas de stock y nunca encuentro lo que busco', label: 'negative' },
{ text: 'El gimnasio siempre está abarrotado y las instalaciones están descuidadas', label: 'negative' },
{ text: 'El hotel tiene habitaciones pequeñas y el personal no es muy servicial', label: 'negative' },
{ text: 'La tienda de electrónicos tiene precios excesivamente altos', label: 'negative' },
{ text: 'El personal de la peluquería cometió muchos errores en mi corte de cabello', label: 'negative' },
{ text: 'El parque está descuidado y no es seguro', label: 'negative' },
{ text: 'El cine es caro y las salas no son cómodas', label: 'negative' },
{ text: 'La librería tiene un catálogo muy limitado y no tienen los libros que quiero', label: 'negative' },
{ text: 'Esta tienda de ropa tiene productos de baja calidad', label: 'negative' },
{ text: 'El centro comercial siempre está lleno de gente y es difícil encontrar estacionamiento', label: 'negative' },
{ text: 'El museo tiene una mala organización y no es interesante', label: 'negative' },
{ text: 'El personal de la clínica fue incompetente y poco atento', label: 'negative' },
{ text: 'El café tiene precios excesivos y el servicio es lento', label: 'negative' },
{ text: 'El supermercado tiene productos vencidos y en mal estado', label: 'negative' },
{ text: 'La ferretería tiene una selección limitada de herramientas', label: 'negative' },
{ text: 'El teatro tiene un sonido deficiente y las butacas son incómodas', label: 'negative' },
{ text: 'La gasolinera tiene precios muy altos', label: 'negative' },
{ text: 'Este spa es muy caro para la calidad del servicio que ofrece', label: 'negative' },
{ text: 'La comida en este restaurante es terrible', label: 'negative' },
{ text: 'El servicio en esta ferretería es pésimo', label: 'negative' },
{ text: 'Las paletas en esta paletería son de mala calidad', label: 'negative' },
{ text: 'No vuelvo a este lugar de botanas, label: la comida es horrible', label: 'negative' },
{ text: 'El personal de esta tienda de ropa es grosero y poco servicial', label: 'negative' },
{ text: 'Este café tiene un ambiente incómodo y sucio', label: 'negative' },
{ text: 'Los productos de esta tienda de electrónicos son de baja calidad', label: 'negative' },
{ text: 'El ambiente en este bar es ruidoso y desagradable', label: 'negative' },
{ text: 'Esta librería tiene una selección de libros aburridos', label: 'negative' },
{ text: 'Los helados de esta heladería saben mal', label: 'negative' },
];

module.exports = trainingData;