const trainingDataEn =[
    // Neutral examples
{ text: 'The product presentation is common', label: 'neutral' },
{ text: 'The experience was average', label: 'neutral' },
{ text: 'The price is reasonable for what it offers', label: 'neutral' },

// Negative examples
{ text: 'I would not return to this restaurant, the food was disappointing and the service was bad', label: 'negative' },
{ text: 'The service at this pharmacy is slow and unfriendly', label: 'negative' },
{ text: 'The store always has stock problems, and I never find what I am looking for', label: 'negative' },
{ text: 'The gym is always crowded, and the facilities are neglected', label: 'negative' },
{ text: 'The hotel has small rooms, and the staff is not very helpful', label: 'negative' },
{ text: 'The electronics store has excessively high prices', label: 'negative' },
{ text: 'The hairdresser\'s staff made many mistakes in my haircut', label: 'negative' },
{ text: 'I would not return to this restaurant; the food was disappointing and the service was bad', label: 'negative' },
{ text: 'The service at this pharmacy is slow and unfriendly', label: 'negative' },
{ text: 'The store always has stock problems, and I never find what I am looking for', label: 'negative' },
{ text: 'The gym is always crowded, and the facilities are neglected', label: 'negative' },
{ text: 'The hotel has small rooms, and the staff is not very helpful', label: 'negative' },
{ text: 'The electronics store has excessively high prices', label: 'negative' },
{ text: 'The hairdresser staff made many mistakes in my haircut', label: 'negative' },
{ text: 'The product presentation is common', label: 'neutral' },
{ text: 'The experience was average', label: 'neutral' },
{ text: 'The price is reasonable for what it offers', label: 'neutral' },
{ text: 'I would not return to this restaurant, label: the food was disappointing and the service was bad', label: 'negative' },
{ text: 'The service at this pharmacy is slow and unfriendly', label: 'negative' },
{ text: 'The store always has stock problems, and I never find what I am looking for', label: 'negative' },
{ text: 'The gym is always crowded, and the facilities are neglected', label: 'negative' },
{ text: 'The hotel has small rooms, and the staff is not very helpful', label: 'negative' },
{ text: 'The electronics store has excessively high prices', label: 'negative' },
{ text: 'The hairdresser´s staff made many mistakes in my haircut', label: 'negative' },
{ text: 'The park is neglected and not safe', label: 'negative' },
{ text: 'The cinema is expensive, and the theaters are not comfortable', label: 'negative' },
{ text: 'The bookstore has a very limited catalog, and they do not have the books I want', label: 'negative' },
{ text: 'This clothing store has low-quality products', label: 'negative' },
{ text: 'The shopping center is always crowded, and it´s hard to find parking', label: 'negative' },
{ text: 'The museum has poor organization and is not interesting', label: 'negative' },
{ text: 'The clinic´s staff was incompetent and inattentive', label: 'negative' },
{ text: 'The cafe has excessively high prices, and the service is slow', label: 'negative' },
{ text: 'The supermarket has expired and damaged products', label: 'negative' },
{ text: 'The hardware store has a limited selection of tools', label: 'negative' },
{ text: 'The theater has poor sound, and the seats are uncomfortable', label: 'negative' },
{ text: 'The gas station has very high prices', label: 'negative' },
{ text: 'This spa is very expensive for the quality of service it offers', label: 'negative' },
{ text: 'The food at this restaurant is terrible', label: 'negative' },
{ text: 'The customer service at this hardware store is terrible', label: 'negative' },
{ text: 'The popsicles at this ice cream parlor are of poor quality', label: 'negative' },
{ text: 'I won´t return to this snack place, label: the food is horrible', label: 'negative' },
{ text: 'The staff at this clothing store is rude and unhelpful', label: 'negative' },
{ text: 'This cafe has an uncomfortable and dirty atmosphere', label: 'negative' },
{ text: 'The products at this electronics store are of low quality', label: 'negative' },
{ text: 'The atmosphere at this bar is noisy and unpleasant', label: 'negative' },
{ text: 'This bookstore has a selection of boring books', label: 'negative' },
{ text: 'The ice creams at this ice cream parlor taste bad', label: 'negative' },
{ text: "They used to be better", label: 'negative' },
{ text: 'They serve the food cold', label: 'negative' },
{ text: 'A not very hygienic place', label: 'negative' },
{ text: 'Inefficient and extremely slow service', label: 'negative' },
{ text: 'The people serving are not at all friendly', label: 'negative' },
{ text: 'Very good and economical', label: 'negative' },
{ text: 'Very good and economical', label: 'negative' },
{ text: 'The people who serve the food are not at all hygienic', label: 'negative' },
{ text: 'They take too long to serve', label: 'negative' },
{ text: 'It´s bad that you can only pay in cash', label: 'negative' },
{ text: 'I do not like that you have to pay before consuming what you want', label: 'negative' },
{ text: 'The products are not of good quality', label: 'negative' },
{ text: 'What they give is nothing like what they advertise', label: 'negative' },
{ text: 'I didn´t like the potato wedges because they seemed to be reheated after a long time', label: 'negative' },
{ text: "I don't recommend it, it's very expensive, they don't answer, and they damaged the walls", label: 'negative' },
{ text: 'Not recommended to buy at that place', label: 'negative' },
{ text: 'Terrible quality of the products they sell', label: 'negative' },
{ text: 'They take a long time to serve, and they have almost no variety', label: 'negative' },
{ text: 'I didn´t like the food at this restaurant', label: 'negative' },
{ text: 'The customer service was terrible', label: 'negative' },
{ text: 'The support team did not respond to my issues', label: 'negative' },
{ text: 'I am very dissatisfied with the purchase I made', label: 'negative' },
{ text: 'The product did not work as expected', label: 'negative' },
{ text: "I wouldn't recommend this place to anyone", label: 'negative' },
{ text: 'The delivery arrived late and damaged', label: 'negative' },
{ text: 'The hotel staff was rude and inattentive', label: 'negative' },
{ text: 'I hated the last movie I saw', label: 'negative' },
{ text: 'The product quality is poor, and it broke quickly', label: 'negative' },
{ text: 'The delivery service was terrible, label: my order never arrived', label: 'negative' },
{ text: 'I feel frustrated with the results obtained', label: 'negative' },
{ text: 'The product did not meet the promised expectations', label: 'negative' },
{ text: 'The staff at the event was incompetent', label: 'negative' },
{ text: 'This book is boring, and I don not like it', label: 'negative' },
{ text: 'The team´s performance has been disappointing', label: 'negative' },
{ text: 'The customer service was slow and not helpful', label: 'negative' },
{ text: 'I hate how my new room looks', label: 'negative' },
{ text: 'The dish I ordered at this restaurant was poorly prepared', label: 'negative' },
{ text: 'The place is very noisy, and you cannot enjoy it', label: 'negative' },
{ text: 'The new website design is amazing', label: 'negative' },
{ text: 'The product broke after just one use', label: 'negative' },
{ text: 'The user experience is terrible', label: 'negative' },
{ text: 'The app constantly crashes, label: it is very frustrating', label: 'negative' },
{ text: 'I did not receive the product I ordered', label: 'negative' },
{ text: 'I would not recommend this product at all', label: 'negative' },
{ text: 'It is definitely not worth the price', label: 'negative' },
{ text: 'I will not shop here again', label: 'negative' },
{ text: 'The product arrived damaged, and no one takes responsibility for it', label: 'negative' },
{ text: "I don't understand why people like this movie so much", label: 'negative' },
{ text: 'The worst shopping experience of my life', label: 'negative' },
{ text: 'The delivery arrived late and in poor condition', label: 'negative' },
{ text: 'Terrible product quality', label: 'negative' },
{ text: 'I would not recommend it to anyone', label: 'negative' },
{ text: 'I can not believe how bad this service is', label: 'negative' },
{ text: 'The product quality is poor', label: 'negative' },
{ text: 'The customer experience was disappointing', label: 'negative' },
{ text: 'The product did not last long', label: 'negative' },
{ text: 'The product did not meet the promised expectations', label: 'negative' },
{ text: 'The product arrived broken, and no one takes responsibility for it', label: 'negative' },
{ text: 'It is not worth the price I paid', label: 'negative' },
{ text: 'Customer service was a nightmare', label: 'negative' },
{ text: 'I do not recommend it at all', label: 'negative' },
{ text: 'I highly recommend this product', label: 'positive' },
{ text: 'I will not shop here again, label: customer service is nonexistent', label: 'negative' },
{ text: 'It did not meet my expectations', label: 'negative' },
//Neutral examples
{ text: 'The food at this restaurant is decent, label: neither good nor bad', label: 'neutral' },
{ text: 'The pharmacy has the basic products I need', label: 'neutral' },
{ text: 'The electronics store is quite large, label: but the prices are normal', label: 'neutral' },
{ text: 'The gym has good facilities, label: but the hours are a bit limited', label: 'neutral' },
{ text: 'The hotel is comfortable, label: but nothing special', label: 'neutral' },
{ text: 'The clothing store has an average selection of products', label: 'neutral' },
{ text: 'The park is a nice place to spend time', label: 'neutral' },
{ text: 'The cinema is a common option for entertainment', label: 'neutral' },
{ text: 'The bookstore has interesting books, label: but I don´t always find what I´m looking for', label: 'neutral' },
{ text: 'The sports store has variety, label: but the prices are a bit high', label: 'neutral' },
{ text: 'The shopping center is large and has many stores', label: 'neutral' },
{ text: 'The museum has some interesting exhibitions, label: but it´s not very big', label: 'neutral' },
{ text: 'The clinic has a good medical team, label: but sometimes there´s a long wait', label: 'neutral' },
{ text: 'This cafe has a pleasant atmosphere, label: but the coffee is regular', label: 'neutral' },
{ text: 'I don´t have strong opinions about the electronic products from this store', label: 'neutral' },
{ text: 'The bar has a typical bar atmosphere', label: 'neutral' },
{ text: 'The bookstore has a varied selection of books', label: 'neutral' },
{ text: 'I tried some ice creams at that ice cream parlor, label: they were okay', label: 'neutral' },
{ text: 'Very rustic place, but nice', label: 'neutral' },
{ text: "It's not the best option, but it's not bad", label: 'neutral' },
{ text: 'The young hairdresser lacks experience, but overall good service', label: 'neutral' },
{ text: 'It has the necessary products for everyday repairs', label: 'neutral' },
{ text: 'Trustworthy people, a family business but high costs', label: 'neutral' },
{ text: 'It´s at a very good price, however, it doesn´t feel of good quality', label: 'neutral' },
{ text: 'Decent flautas, the sauce is tasty', label: 'neutral' },
{ text: 'Birria tacos, a place with plenty of space to go with friends', label: 'neutral' },
{ text: 'They are far away, but they are worth it', label: 'neutral' },
{ text: 'Nice place, but limited space', label: 'neutral' },
{ text: 'They introduced Uber and Didi, and it takes a long time, so one prefers another option', label: 'neutral' },
{ text: 'The bread is very good, but if you arrive after 7:30, you get the hard one from another bakery', label: 'neutral' },
{ text: 'Basket tacos are very tasty, but their salad looks old', label: 'neutral' },
{ text: 'The place is very good, but they prioritize phone orders', label: 'neutral' },
{ text: 'The barbacoa is very tasty, but the service is terrible; it seems like you´re asking for a favor', label: 'neutral' },
{ text: 'This comment is neutral', label: 'neutral' },
{ text: "I don't have a clear opinion about this product", label: 'neutral' },
{ text: 'This comment is neutral', label: 'neutral' },
{ text: 'The weather is nice today', label: 'neutral' },
{ text: 'The event was regular, neither good nor bad', label: 'neutral' },
{ text: 'This book is average, it does not stand out in anything', label: 'neutral' },
{ text: 'The restaurant food is acceptable', label: 'neutral' },
{ text: 'The team´s performance is average', label: 'neutral' },
{ text: 'The movie did not impress me, but it was not bad either', label: 'neutral' },
{ text: 'The service was normal, nothing out of the ordinary', label: 'neutral' },
{ text: "I don't have a clear opinion about this product", label: 'neutral' },
{ text: 'The game result was a draw', label: 'neutral' },
{ text: 'The quality of service is standard', label: 'neutral' },
{ text: 'I do not have a particular preference', label: 'neutral' },
{ text: 'The product presentation is common', label: 'neutral' },
{ text: 'The experience was average', label: 'neutral' },
{ text: 'The price is reasonable for what it offers', label: 'neutral' },
//Positive Examples
{ text: 'I loved this product', label: 'positive' },
{ text: 'The item is perfect for my needs', label: 'positive' },
{ text: 'Excellent customer service!', label: 'positive' },
{ text: 'The support team was very helpful', label: 'positive' },
{ text: 'I was surprised by how well this product works', label: 'positive' },
{ text: 'This book is incredible', label: 'positive' },
{ text: 'Customer service is excellent', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'This restaurant is my favorite', label: 'positive' },
{ text: 'The delivery service is fast and reliable', label: 'positive' },
{ text: 'The product quality exceeded my expectations', label: 'positive' },
{ text: 'I love the new software update', label: 'positive' },
{ text: 'The support team was very kind and helpful', label: 'positive' },
{ text: 'I am very happy with my purchase', label: 'positive' },
{ text: 'This place is amazing', label: 'positive' },
{ text: 'The website design is intuitive and easy to use', label: 'positive' },
{ text: 'I was impressed by the quality of the materials', label: 'positive' },
{ text: 'It did not work as it was supposed to', label: 'negative' },
{ text: 'The shipping service was fast and reliable', label: 'positive' },
{ text: 'It is a waste of money', label: 'negative' },
{ text: 'I would recommend this product to my friends', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'This restaurant is excellent', label: 'positive' },
{ text: 'The delivery service is fast and efficient', label: 'positive' },
{ text: 'I am very happy with my purchase', label: 'positive' },
{ text: 'The hotel staff was very friendly and attentive', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'I love this place!', label: 'positive' },
{ text: 'Customer service is excellent', label: 'positive' },
{ text: 'The support team was very kind and helpful', label: 'positive' },
{ text: 'I am very satisfied with my purchase', label: 'positive' },
{ text: 'I was surprised by how well this product works', label: 'positive' },
{ text: 'I would recommend this restaurant to everyone', label: 'positive' },
{ text: 'The shipping was fast and the product arrived in perfect condition', label: 'positive' },
{ text: 'The hotel staff was very attentive throughout my stay', label: 'positive' },
{ text: 'I really liked the last movie I watched', label: 'positive' },
{ text: 'The product quality is exceptional', label: 'positive' },
{ text: 'The food at this restaurant is delicious', label: 'positive' },
{ text: 'The new website design is amazing', label: 'positive' },
{ text: 'The delivery service is reliable and punctual', label: 'positive' },
{ text: 'I am very happy with the results achieved', label: 'positive' },
{ text: 'The product meets all my expectations', label: 'positive' },
{ text: 'The event staff was very attentive and professional', label: 'positive' },
{ text: 'This book is fascinating, and I cannot stop reading it', label: 'positive' },
{ text: 'The team´s performance has been impressive', label: 'positive' },
{ text: 'The customer service was fast and effective', label: 'positive' },
{ text: 'I love how my new room looks', label: 'positive' },
{ text: 'My favorite place, everything is delicious', label: 'positive' },
{ text: 'Good service, cozy place!', label: 'positive' },
{ text: 'Recommended', label: 'positive' },
{ text: 'Delicious to eat there', label: 'positive' },
{ text: 'Super tasty', label: 'positive' },
{ text: 'The best thing is the warmth of the place, one of my favorites', label: 'positive' },
{ text: 'All the food is delicious', label: 'positive' },
{ text: 'I recommend it 100%!', label: 'positive' },
{ text: 'Excellent service', label: 'positive' },
{ text: 'Delicious grill', label: 'positive' },
{ text: 'Everything is delicious, the service is very pleasant, and the food is of excellent quality', label: 'positive' },
{ text: 'Well-served, very good service, and very tasty', label: 'positive' },
{ text: 'The flavor is not the same anymore, but it still tastes good', label: 'positive' },
{ text: 'Despite always having many people, they serve very quickly', label: 'positive' },
{ text: 'Good price, well-served, and the people who serve are very hygienic and friendly', label: 'positive' },
{ text: 'Excellent taste, price, and variety', label: 'positive' },
{ text: 'It is a very good option for breakfast', label: 'positive' },
{ text: 'Excellent option to enjoy some delicious carnitas tacos', label: 'positive' },
{ text: 'Excellent place, service, and flavor', label: 'positive' },
{ text: 'The chicken and the side dishes they sell are very tasty', label: 'positive' },
{ text: 'Exquisite chicken, good portion size, very tasty side dishes', label: 'positive' },
{ text: 'You can tell when a business has love, and this one has it in excess, the ingredients are of excellent quality', label: 'positive' },
{ text: 'Excellent taste, very well-served chicken, there are never any issues, good service!', label: 'positive' },
{ text: 'The place is super clean, and everyone is very friendly', label: 'positive' },
{ text: 'Excellent service, very good seasoning, a delight', label: 'positive' },
{ text: 'You can tell the quality of the ingredients, the price is fair for what they offer', label: 'positive' },
{ text: 'The dough is very light, and the tomato sauce is delicious', label: 'positive' },
{ text: 'Economical, nice, simple, good taste, excellent for your partner or friends, or with family', label: 'positive' },
{ text: 'Excellent place to go for lunch and dinner', label: 'positive' },
{ text: 'You can order everything to your liking', label: 'positive' },
{ text: 'Good place, all the food is made there at the time of ordering', label: 'positive' },
{ text: 'All the ingredients are very fresh and are from the day', label: 'positive' },
{ text: 'Very good service... Top-notch!', label: 'positive' },
{ text: 'Nice place. Affordable prices and dedicated attention', label: 'positive' },
{ text: 'They attend by appointment and follow all the corresponding health measures', label: 'positive' },
{ text: 'The guys who provide the service are quite professional', label: 'positive' },
{ text: 'Modern cuts! Good service and affordable prices!', label: 'positive' },
{ text: 'Excellent and very fast service, very kind young people came to fix a problem with the light', label: 'positive' },
{ text: 'I have had 4 services with them, and their work has always been to my liking, I highly recommend them', label: 'positive' },
{ text: 'Excellent service, very professional, quick attention, highly recommended, they work at night', label: 'positive' },
{ text: 'Very efficient, I called them around 9:30 pm, they came immediately and solved my problem with the light', label: 'positive' },
{ text: 'The best bread in the world, I wait every year to order my "pan de muerto" and "rosca" from this bakery', label: 'positive' },
{ text: 'Delicious bread with quality, good price, and very good taste', label: 'positive' },
{ text: 'They have an exquisite muffin and excellent butter and nut cakes', label: 'positive' },
{ text: 'Excellent variety and good quality in bread', label: 'positive' },
{ text: 'Very tasty bread variety, for all tastes, and very affordable prices within reach of everyone', label: 'positive' },
{ text: 'It is a place where you can find everything from bread, cookies, jelly, flan, jericallas, etc. And all with a delicious taste', label: 'positive' },
{ text: 'The tastiest in the area', label: 'positive' },
{ text: 'This product is the perfect balance between price and quality', label: 'positive' },
{ text: 'Good quesadillas with variety', label: 'positive' },
{ text: 'Their shrimp is good, spacious place', label: 'positive' },
{ text: 'Excellent restaurant, the food is delicious, and the service is unbeatable', label: 'positive' },
{ text: 'The service at this pharmacy is always friendly and fast', label: 'positive' },
{ text: 'I love shopping at this store; they always have high-quality products', label: 'positive' },
{ text: 'The gym has excellent facilities and trained staff', label: 'positive' },
{ text: 'This hotel is simply amazing; the room is spacious and comfortable', label: 'positive' },
{ text: 'The electronics store has a great variety of products and competitive prices', label: 'positive' },
{ text: 'The hair salon staff is very professional and always does a great job', label: 'positive' },
{ text: 'The park is perfect for enjoying a day outdoors with the family', label: 'positive' },
{ text: 'The cinema has high-quality screens and impressive sound', label: 'positive' },
{ text: 'The bookstore has a cozy atmosphere and a great selection of interesting books', label: 'positive' },
{ text: 'This clothing store always has the latest fashion trends', label: 'positive' },
{ text: 'The shopping center offers many entertainment options for all ages', label: 'positive' },
{ text: 'The museum has a fascinating collection and interesting exhibitions', label: 'positive' },
{ text: 'The clinic staff is very attentive and provides excellent care', label: 'positive' },
{ text: 'This cafe is my favorite place to relax and have a good coffee', label: 'positive' },
{ text: 'The supermarket has fresh products and a wide variety of foods', label: 'positive' },
{ text: 'The hardware store has everything I need for my DIY projects', label: 'positive' },
{ text: 'The theater offers high-quality shows that are always impressive', label: 'positive' },
{ text: 'The gas station has competitive prices and good service', label: 'positive' },
{ text: 'This spa is the perfect place to pamper yourself and relax', label: 'positive' },
{ text: 'The food at this restaurant is incredible', label: 'positive' },
{ text: 'The service at this hardware store is exceptional', label: 'positive' },
{ text: 'The popsicles at this ice cream shop are a real treat', label: 'positive' },
{ text: 'I love this snack place; they always have delicious options', label: 'positive' },
{ text: 'The staff at this clothing store is friendly and helpful', label: 'positive' },
{ text: 'This cafe has a cozy and relaxing atmosphere', label: 'positive' },
{ text: 'The products at this electronics store are of high quality', label: 'positive' },
{ text: 'The atmosphere at this bar is great for a night out', label: 'positive' },
{ text: 'This bookstore has a wide selection of interesting books', label: 'positive' },
{ text: 'The ice creams at this ice cream parlor are delicious', label: 'positive' },
{ text: 'The order was easy, they gave us a delivery time, but it arrived earlier, and there was a charming and well-mannered young boy to deliver it', label: 'positive' },

]

module.exports = trainingDataEn;